# This workflow will upload a Python Package when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python distributions to PyPI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-n-publish:
    name: Build and deploy package
    # runs-on: ubuntu-18.04
    # steps:
    #   - uses: actions/checkout@master
    #   - name: Initialize Python 3.7
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.7
    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install flake8
    #   - name: Lint with flake8
    #     run: |
    #       # stop the build if there are Python syntax errors or undefined names
    #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #       # exit-zero treats all errors as warnings.
    #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #   - name: Build binary wheel and a source tarball
    #     run: python setup.py sdist
    #   - name: Publish 
    #     uses: pypa/gh-action-pypi-publish@master
    #     with:
    #       password: ${{ secrets.test_pypi_password }}
    #       repository_url: https://pypi.org/legacy/